# Build settings
markdown: kramdown
permalink: pretty
permalink: /:year/:month/:day/:title/

baseurl: "R-S-Automotive-Services"
future: false #hides future blogs
# Enable Liquid processing in markdown files
kramdown:
  parse_block_html: true

