# Build settings
markdown: kramdown
permalink: pretty
permalink: /:year/:month/:day/:title/

baseurl: ""
future: false #hides future blogs
# Enable Liquid processing in markdown files
kramdown:
  parse_block_html: true
